---
# tasks/CentOS/rabbit.yml: Deploy RabbitMQ
# Specific to CentOS

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: install esl key
    rpm_key: state=present key=http://packages.erlang-solutions.com/rpm/erlang_solutions.asc

  - name: install the esl repo for erlang
    template:
      src: esl-erlang.repo.j2
      dest: /etc/yum.repos.d/esl-erlang.repo
      mode: 0644
  
  - name: install Erlang from the esl repo
    yum:
      name:
        - erlang
      state: present
      update_cache: yes
      disablerepo: "{{ centos_repository }}"


  - name: Ensure RabbitMQ is installed
    yum:
      name:
        - rabbitmq-server
      state: present
      enablerepo: "{{ centos_repository }}"
